# This is a basic workflow to help you get started with Actions

name: macos-static-build

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  macosBuild:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true 
          xcode-version: latest-stable

      - name: Building
        run: |
         sh ./compileAndBuildVLCKit.sh -x -v -b -a x86_64 
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: build
          path: ./
          if-no-files-found: error
